# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '王小红测试' do
    pod 'Masonry', '~> 1.1.0'
    pod 'ReactiveObjC'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 王小红测试

  target '王小红测试Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '王小红测试UITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  

end
